name: LiaScript to SCORM Automation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Download LiaScript Exporter
      run: |
        wget https://github.com/LiaScript/LiaScript-Exporter/releases/download/v1.7.0/lia-linux
        chmod +x lia-linux

    - name: Build SCORM Package
      run: ./lia-linux -i README.md --format scorm1.2 --output scorm-package

    - name: Upload SCORM as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: scorm-package
        path: scorm-package
